### ISSUE TITLE
MMS for Tensorflow

### ISSUE THREAD

**Issue by MohammadOmr** [kubeflow/kfserving#1391]
/kind bug

**What steps did you take and what happened:**
I created an inference service with a Tensorflow predictor without a uri, since I was planning to add trained model CRD to the inference service.

**What did you expect to happen:**
for the inference service to serve multiple tensorflow models 

**Anything else you would like to add:**
kfserving fails to detect the inference service as a hosting one, and treats it as a single model inference service and so it throws an error complaining that it couldn't download the model.

**Environment:**

- Knative Version:0.19
- KFServing Version: v0.5.0-rc2
- Kubeflow version:
- Kubernetes version:1.19

**Comment by yuzliu** [comment]
Hi @MohammadOmr tensorflow's default model server tfserving is does not implement KFServing v2 protocol so it is not integrated with MMS. Please see: https://github.com/kubeflow/kfserving/blob/master/docs/MULTIMODELSERVING_GUIDE.md#integration-with-model-servers for more explanations. 

Triton server can deploy tensorflow model as well, do you think you can use triton instead? We have a readme about how to use triton server with MMS: https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/triton/multimodel

**Comment by MohammadOmr** [comment]
@yuzliu thanks for the reply I already tested with Triton but I kept facing issues in Downloading/loading the model. Some of those issues were caused by Triton requiring a config.pbtxt file and a different folder hierarchy, after solving that 
the agent  kept throwing  errors 
 `anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x169f489]

goroutine 21 [running]:
github.com/kubeflow/kfserving/pkg/agent/storage.FileExists(0xc00039e500, 0x38, 0x3)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/storage/utils.go:27 +0x99
github.com/kubeflow/kfserving/pkg/agent/storage.(*S3ObjectDownloader).GetAllObjects(0xc00045dab0, 0x2020a80, 0xc00000ead0, 0x1, 0x0, 0x1, 0xc000900040, 0x2)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/storage/s3.go:93 +0x2c2
github.com/kubeflow/kfserving/pkg/agent/storage.(*S3Provider).DownloadModel(0xc00075c380, 0x1bdc607, 0xb, 0xc00075e340, 0x7, 0xc0009b0300, 0x1f, 0x1f90f00, 0xc0006425d0)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/storage/s3.go:66 +0x2fe
github.com/kubeflow/kfserving/pkg/agent.(*Downloader).download(0xc0002ea758, 0xc00075e340, 0x7, 0xc0009b0300, 0x1f, 0x2, 0x2)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/downloader.go:74 +0xff
github.com/kubeflow/kfserving/pkg/agent.(*Downloader).DownloadModel(0xc0002ea758, 0xc00075e340, 0x7, 0xc000115140, 0x0, 0x0)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/downloader.go:50 +0x517
github.com/kubeflow/kfserving/pkg/agent.(*Puller).modelProcessor(0xc0002ea740, 0xc00075e340, 0x7, 0xc00009c1e0)
	/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:130 +0x273
created by github.com/kubeflow/kfserving/pkg/agent.(*Puller).enqueueModelOp
	/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:89 +0x120
`
 some other times 
 `Failed to load model  with status [400] and resp no version is available`
 even though I used the model provided by triton here 
 https://github.com/triton-inference-server/server/tree/master/docs/examples/model_repository
 
 Any idea on what could be causing this issue or what this might be related to

**Comment by yuzliu** [comment]
@MohammadOmr Which version of KFServing you are running?

**Comment by yuzliu** [comment]
@MohammadOmr thanks for reporting we will try to replicate the issue.

**Comment by yuzliu** [comment]
@MohammadOmr could you please post the trainedmodel CR and the triton model you used?

**Comment by MohammadOmr** [comment]
> @MohammadOmr Which version of KFServing you are running?

v0.5.0-rc2

**Comment by MohammadOmr** [comment]
@yuzliu
here's the model that I used from Triton repo 
https://github.com/triton-inference-server/server/tree/master/docs/examples/model_repository/simple_identity

and the trained model CR

`
apiVersion: "serving.kubeflow.org/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "simpleid"
spec:
  inferenceService: image-mms
  model:
    framework: tensorflow
    storageUri: s3://s3averroesai/model/simple_id
`
I also tested with different TF models that worked fine on tfserving and kfserving as single inference service

**Comment by abchoo** [comment]
@MohammadOmr  Could you try changing your storageUri to `s3://bucket/model/simple_id/1/model.savedmodel`? (I assume  1/model.savedmodel is the path to `saved_model.pb` based on the link provided).

**Comment by yuzisun** [comment]
@MohammadOmr Can you try the latest 0.5.0? I think we have fixed it in https://github.com/kubeflow/kfserving/pull/1318

**Comment by yuzliu** [comment]
Please also make sure your inferenceservice uses triton predictor e.g.
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-mms"
spec:
  predictor:
    triton:
      args:
      - --log-verbose=1     
      resources:
        limits:
          cpu: "1"
          memory: 16Gi
        requests:
          cpu: "1"
          memory: 16Gi
```

**Comment by MohammadOmr** [comment]
> @MohammadOmr Can you try the latest 0.5.0 release? I think we have fixed it in #1318



> Please also make sure your inferenceservice uses triton predictor e.g.
> 
> ```
> apiVersion: "serving.kubeflow.org/v1beta1"
> kind: "InferenceService"
> metadata:
>   name: "triton-mms"
> spec:
>   predictor:
>     triton:
>       args:
>       - --log-verbose=1     
>       resources:
>         limits:
>           cpu: "1"
>           memory: 16Gi
>         requests:
>           cpu: "1"
>           memory: 16Gi
> ```

I did try with the example provided in the documentation which has the same inferenceservice as the one you attached
but still faced the same issue

**Comment by yuzisun** [comment]
> > @MohammadOmr Can you try the latest 0.5.0 release? I think we have fixed it in #1318
> 
> > Please also make sure your inferenceservice uses triton predictor e.g.
> > ```
> > apiVersion: "serving.kubeflow.org/v1beta1"
> > kind: "InferenceService"
> > metadata:
> >   name: "triton-mms"
> > spec:
> >   predictor:
> >     triton:
> >       args:
> >       - --log-verbose=1     
> >       resources:
> >         limits:
> >           cpu: "1"
> >           memory: 16Gi
> >         requests:
> >           cpu: "1"
> >           memory: 16Gi
> > ```
> 
> I did try with the example provided in the documentation which has the same inferenceservice as the one you attached
> but still faced the same issue

the same crash stack?

**Comment by MohammadOmr** [comment]
> > > @MohammadOmr Can you try the latest 0.5.0 release? I think we have fixed it in #1318
> > 
> > 
> > > Please also make sure your inferenceservice uses triton predictor e.g.
> > > ```
> > > apiVersion: "serving.kubeflow.org/v1beta1"
> > > kind: "InferenceService"
> > > metadata:
> > >   name: "triton-mms"
> > > spec:
> > >   predictor:
> > >     triton:
> > >       args:
> > >       - --log-verbose=1     
> > >       resources:
> > >         limits:
> > >           cpu: "1"
> > >           memory: 16Gi
> > >         requests:
> > >           cpu: "1"
> > >           memory: 16Gi
> > > ```
> > 
> > 
> > I did try with the example provided in the documentation which has the same inferenceservice as the one you attached
> > but still faced the same issue
> 
> the same crash stack?

In the example provided in the documentation there's a typo in the trainedmodel CR where the platform is declared as pytorch instead of tensorflow however when I tested I got the same crash stack

**Comment by MohammadOmr** [comment]
> @MohammadOmr Can you try the latest 0.5.0 release? I think we have fixed it in #1318

first off there are 4 yaml files not sure which one to use If I need a standalone version

**Comment by yuzisun** [comment]
> > @MohammadOmr Can you try the latest 0.5.0 release? I think we have fixed it in #1318
> 
> first off there are 4 yaml files not sure which one to use If I need a standalone version

Can you follow the standalone install instruction here https://github.com/kubeflow/kfserving#standalone-kfserving-installation to install 0.5.0?

**Comment by MohammadOmr** [comment]
> > > @MohammadOmr Can you try the latest 0.5.0 release? I think we have fixed it in #1318
> > 
> > 
> > first off there are 4 yaml files not sure which one to use If I need a standalone version
> 
> Can you follow the standalone install instruction [here](https://github.com/kubeflow/kfserving#install-kfserving) to install 0.5.0?

I install but now when I create an hosting inferenceservice(v1beta1) it doesn't recognize it as a v1beta1 because it only creates 2 containers instead of three

**Comment by yuzisun** [comment]
> > > > @MohammadOmr Can you try the latest 0.5.0 release? I think we have fixed it in #1318
> > > 
> > > 
> > > first off there are 4 yaml files not sure which one to use If I need a standalone version
> > 
> > 
> > Can you follow the standalone install instruction [here](https://github.com/kubeflow/kfserving#install-kfserving) to install 0.5.0?
> 
> I installed it but now when I create an hosting inferenceservice(v1beta1) it doesn't recognize it as a v1beta1 because it only creates 2 containers instead of three

@MohammadOmr yes as it is alpha feature you would need to change the `multiModelServer` flag to be true, see the doc [here](https://github.com/kubeflow/kfserving/blob/master/docs/MULTIMODELSERVING_GUIDE.md#integration-with-model-servers)

**Comment by MohammadOmr** [comment]
> > > > > @MohammadOmr Can you try the latest 0.5.0 release? I think we have fixed it in #1318
> > > > 
> > > > 
> > > > first off there are 4 yaml files not sure which one to use If I need a standalone version
> > > 
> > > 
> > > Can you follow the standalone install instruction [here](https://github.com/kubeflow/kfserving#install-kfserving) to install 0.5.0?
> > 
> > 
> > I installed it but now when I create an hosting inferenceservice(v1beta1) it doesn't recognize it as a v1beta1 because it only creates 2 containers instead of three
> 
> @MohammadOmr yes as it is alpha feature you would need to change the `multiModelServer` flag to be true, see the doc [here](https://github.com/kubeflow/kfserving/blob/master/docs/MULTIMODELSERVING_GUIDE.md#integration-with-model-servers)

setting the flag to true worked but still downloading the model sometimes throws the following error 
`
{"level":"error","ts":"2021-02-21T14:10:52.222Z","caller":"agent/puller.go:134","msg":"Failed to download model trinoexp with err failed to download model: failed to download model: unable to get batch objects file is already created: mkdir /mnt/models/trinoexp/1/model.savedmodel: not a directory","stacktrace":"github.com/kubeflow/kfserving/pkg/agent.(*Puller).modelProcessor\n\t/go/src/github.com/kubeflow/kfserving/pkg/agent/puller.go:134"}
`
