### ISSUE TITLE
Getting PredictorHostnameUnknown error when using custom image in azure container

### ISSUE THREAD

**Issue by sammy04** [kubeflow/kfserving#576]
I have deployed kfserving using kubeflow. I am using custom predictor with image in azure container registry. I have provided serviceaccount in custom yaml. But I am getting below error
```
Status:
  Canary:
  Conditions:
    Last Transition Time:  2019-11-26T07:17:58Z
    Message:               Configuration "model-predictor-default" does not have any ready Revision.
    Reason:                RevisionMissing
    Status:                False
    Type:                  DefaultPredictorReady
    Last Transition Time:  2019-11-26T07:17:58Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  Ready
    Last Transition Time:  2019-11-26T07:17:57Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  RoutesReady
  Default:
    Predictor:
```

custom inference service yaml file:
```
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: model
spec:
  default:
    predictor:
      custom:
        container:
          image: myregistry.azurecr.io/custompredict:1
          env:
            - name: STORAGE_URI
              value: "https://mystorageaccount.blob.core.windows.net/mystorage/mymodel"
      serviceAccountName: azuresa
```
azure secret yaml file:
```
apiVersion: v1
kind: Secret
metadata:
  name: azcreds
type: Opaque
data:
  AZ_CLIENT_ID: XXXX
  AZ_CLIENT_SECRET: XXXX
  AZ_SUBSCRIPTION_ID: XXXX
  AZ_TENANT_ID: XXXX
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azures
secrets:
  - name: azcreds
```

Both pod and deployment are not getting created. 
I have tried with separate installation of istio 1.1.7, knative 0.8 and kfserving, but still getting same error.

However when i use any of the GCR image and storage given in sample examples, it works perfectly.

Do I need to change any other configuration file ?

**Comment by ellis-bigelow** [comment]
Can you check the logs of the kfserving controller?

**Comment by sammy04** [comment]
Log from event:
```
2s          Warning   InternalError             Revision        unsupported status code 401; body:
8s          Normal    Created                   Service         Created Configuration "model-predictor-default"
7s          Normal    Created                   Service         Created Route "model-predictor-default"
7s          Normal    Created                   Configuration   Created Revision "model-predictor-default-zcw8x"
7s          Normal    Updated                   Service         Updated Service "model-predictor-default"
7s          Warning   UpdateFailed              Configuration   Failed to update status for Configuration "model-predictor-default": Operation cannot be fulfilled on configurations.serving.knative.dev "model-predictor-default": the object has been modified; please apply your changes to the latest version and try again
7s          Warning   LatestCreatedFailed       Configuration   Latest created revision "model-predictor-default-zcw8x" has failed
7s          Warning   UpdateFailed              Route           Failed to update status for Route "model-predictor-default": Operation cannot be fulfilled on routes.serving.knative.dev "model-predictor-default": the object has been modified; please apply your changes to the latest version and try again
7s          Warning   InternalError             Service         Operation cannot be fulfilled on configurations.serving.knative.dev "model-predictor-default": the object has been modified; please apply your changes to the latest version and try again
7s          Warning   UpdateFailed              Service         Failed to update status for Service "model-predictor-default": Operation cannot be fulfilled on services.serving.knative.dev "model-predictor-default": the object has been modified; please apply your changes to the latest version and try again
```
[kfserving controller log.txt](https://github.com/kubeflow/kfserving/files/3896633/kfserving.controller.log.txt)
```
{"level":"error","ts":1574847472.461576,"logger":"kfserving-controller","msg":"Failed to reconcile","error":"Operation cannot be fulfilled on services.serving.knative.dev \"model-predictor-default\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/kfserving/pkg/controller/inferenceservice.(*ReconcileService).Reconcile\n\t/go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/controller.go:147\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

**Comment by sammy04** [comment]
as per below error there is problem while accessing azure container registry. However I have attached ACR.
```unsupported status code 401; body:```

I also tried sklearn sample example with private azure storage and azure service account. But private storage is not accessible. As per below error it seems that python predictor program is not getting azure credential values from environment.
```"Azure credentials not found, retrying anonymous access"```.

azure service account is not found as per below log.
```
{"level":"info","ts":1574868049.6914406,"logger":"Reconciler","msg":"Updating service","namespace":"default","name":"sklearn-iris-predictor-default"}
{"level":"error","ts":1574868050.0972683,"logger":"CredentialBulder","msg":"Failed to find service account","ServiceAccountName":"azuresa","error":"ServiceAccount \"azuresa\" not found","stacktrace":"github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/credentials.(*CredentialBuilder).CreateSecretVolumeAndEnv\n\t/go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/credentials/service_account_credentials.go:83\ngithub.com/kubeflow/kfserving/pkg/webhook/admission/pod.(*StorageInitializerInjector).InjectStorageInitializer\n\t/go/src/github.com/kubeflow/kfserving/pkg/webhook/admission/pod/storage_initializer_injector.go:162\ngithub.com/kubeflow/kfserving/pkg/webhook/admission/pod.(*StorageInitializerInjector).InjectStorageInitializer-fm\n\t/go/src/github.com/kubeflow/kfserving/pkg/webhook/admission/pod/mutator.go:86\ngithub.com/kubeflow/kfserving/pkg/webhook/admission/pod.(*Mutator).mutate\n\t/go/src/github.com/kubeflow/kfserving/pkg/webhook/admission/pod/mutator.go:90\ngithub.com/kubeflow/kfserving/pkg/webhook/admission/pod.(*Mutator).Handle\n\t/go/src/github.com/kubeflow/kfserving/pkg/webhook/admission/pod/mutator.go:57\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).handleMutating\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:133\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:120\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:93\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2337\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2694\nnet/http.initNPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3260\nnet/http.(Handler).ServeHTTP-fm\n\t/usr/local/go/src/net/http/h2_bundle.go:5475\nnet/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5760"}
{"level":"info","ts":1574868170.2080712,"logger":"CredentialBulder","msg":"found secret","SecretName":"azcreds"}
{"level":"info","ts":1574868170.208252,"logger":"CredentialBulder","msg":"Setting secret envs for azure","AzureSecret":"azcreds"}
{"level":"info","ts":1574868170.20827,"logger":"CredentialBulder","msg":"found secret","SecretName":"azuresa-token-n795v"}
```

**Comment by yuzisun** [comment]
@sammy04 are you using the kfserving version part of current kubeflow installation ? this issue has been fixed in 0.2.1+.

**Comment by sammy04** [comment]
@yuzisun I tried with kfserving 0.2.1, istio 1.1.7, knative 0.8. But still getting ContainerMissing error.
```
NAME                                                         CONFIG NAME               K8S SERVICE NAME   GENERATION   READY   REASON
revision.serving.knative.dev/model-predictor-default-5wk27   model-predictor-default                      1            False   ContainerMissing

NAME                                                        LATESTCREATED                   LATESTREADY   READY   REASON
configuration.serving.knative.dev/model-predictor-default   model-predictor-default-5wk27                 False   RevisionFailed

NAME                                                URL                                                  READY   REASON
route.serving.knative.dev/model-predictor-default   http://model-predictor-default.default.example.com   False   RevisionMissing

NAME                                                  URL                                                  LATESTCREATED                   LATESTREADY   READY   REASON
service.serving.knative.dev/model-predictor-default   http://model-predictor-default.default.example.com   model-predictor-default-5wk27                 False   RevisionMissing
```

**Comment by yuzisun** [comment]
@sammy04 are you still seeing this error?
```
{"level":"error","ts":1574868050.0972683,"logger":"CredentialBulder","msg":"Failed to find service account","ServiceAccountName":"azuresa","error":"ServiceAccount \"azuresa\" not found","stacktrace":"github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/credentials.(*CredentialBuilder).CreateSecretVolumeAndEnv\n\t/go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/credentials/service_account_credentials.go:83\ngithub.com/kubeflow/kfserving/pkg/webhook/admission/pod.(*StorageInitializerInjector).InjectStorageInitializer\n\t/go/src/github.com/kubeflow/kfserving/pkg/webhook/admission/pod/storage_initializer_injector.go:162\ngithub.com/kubeflow/kfserving/pkg/webhook/admission/pod.(*StorageInitializerInjector).InjectStorageInitializer-fm\n\t/go/src/github.com/kubeflow/kfserving/pkg/webhook/admission/pod/mutator.go:86\ngithub.com/kubeflow/kfserving/pkg/webhook/admission/pod.(*Mutator).mutate\n\t/go/src/github.com/kubeflow/kfserving/pkg/webhook/admission/pod/mutator.go:90\ngithub.com/kubeflow/kfserving/pkg/webhook/admission/pod.(*Mutator).Handle\n\t/go/src/github.com/kubeflow/kfserving/pkg/webhook/admission/pod/mutator.go:57\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).handleMutating\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:133\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:120\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:93\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2337\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2694\nnet/http.initNPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3260\nnet/http.(Handler).ServeHTTP-fm\n\t/usr/local/go/src/net/http/h2_bundle.go:5475\nnet/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5760"}
```

**Comment by sammy04** [comment]
@yuzisun No, I am not getting "Failed to find service account" error with kfserving 0.2.1. Hence able to access private azure blob storage. (with sample public predictor image given in examples)

But I am still unable to use private ACR custom predictor image.

**Comment by yuzisun** [comment]
what's the full output of `kubectl get revision model-predictor-default-5wk27 -o yaml` ?

**Comment by sammy04** [comment]
@yuzisun 
revision yaml file:
[revision.txt](https://github.com/kubeflow/kfserving/files/3906339/revision.txt)

**Comment by sammy04** [comment]
it got resolved after adding imagepullsecret.
thanks @yuzisun

**Comment by SarathChandran** [comment]
@sammy04 Could you tell where did you add imagepullsecret in you predictor spec?

**Comment by sammy04** [comment]
@SarathChandran 
I created imagepullsecret and added that to service account yaml file as below.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azuresa
secrets:
  - name: azcreds
imagePullSecrets:
  - name: imagepullsecret
```
